# Generated by Django 6.0.3 on 2026-04-24 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_library_is_default_alter_song_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='task_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
