# Generated by Django 6.0.3 on 2026-04-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_song_song_url_song_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='additional',
            field=models.TextField(blank=True, null=True),
        ),
    ]
