# Generated by Django 6.0.3 on 2026-04-30 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0005_alter_song_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Processing', 'Processing'), ('Completed', 'Completed')], default='Pending', max_length=50),
        ),
    ]
